### PR TITLE
fix negative integral windup limits

### PR DESCRIPTION
**Pull request by shiukaheng**
Fix for #5

### CODE REVIEW

**Comment by Researcherdynamics** [comment]
> Fix for #5

Thank you, it works

**Comment by PowerBroker2** [comment]
Thank you for the PR, but I'm starting to wonder if this fix will continue to work if `outputMin` is positive. Perhaps a more complex solution is needed? Been a while since I've looked at this lib so external input is more than welcome

**Comment by PowerBroker2** [comment]
I'll just merge now and fix later if it's an issue

**Comment by shiukaheng** [comment]
Sorry, busy with work atm, I will test it out later with positive outputMin values to see if it works fine :)

**Pull request merged**
